name: Unit Tests

on:
  pull_request: 
    types:
        - opened
        - synchronize
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Install dependencies'
        shell: pwsh
        run: |
          dotnet restore

      - name: 'Build'
        shell: pwsh
        run: |
          dotnet build
          
      - name: 'Test'
        shell: pwsh
        run: |
          dotnet test